In [0]:
pip install openpyxl

Python interpreter will be restarted.
Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Python interpreter will be restarted.

In [0]:
import requests
import os

if not os.path.isfile("./Airport_Data.xlsx"):
    r = requests.get("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/analysing-spreadsheet-data-with-python/Airport_Data.xlsx")
    f = open("./Airport_Data.xlsx", mode = "wb+")
    f.write(r.content)
    f.close()

In [0]:
import pandas as pd

df_facilities = pd.read_excel("./Airport_Data.xlsx", sheet_name="Facilities")

In [0]:
df_facilities

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [0]:
df_facilities["Type"]

Out[5]: 0            AIRPORT
1            AIRPORT
2            AIRPORT
3      SEAPLANE BASE
4            AIRPORT
           ...
746    SEAPLANE BASE
747          AIRPORT
748          AIRPORT
749    SEAPLANE BASE
750          AIRPORT
Name: Type, Length: 751, dtype: object

In [0]:
df_facilities["Type"].unique()

Out[6]: array(['AIRPORT', 'SEAPLANE BASE', 'HELIPORT'], dtype=object)

In [0]:
df_facilities["Type"] == 'SEAPLANE BASE'

Out[7]: 0      False
1      False
2      False
3       True
4      False
       ...
746     True
747    False
748    False
749     True
750    False
Name: Type, Length: 751, dtype: bool

In [0]:
df_facilities[df_facilities['Type']=='SEAPLANE BASE']

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
5,50022.*C,SEAPLANE BASE,'KQA,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS EAST,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
8,50027.52*C,SEAPLANE BASE,'Z33,3/30/2017,AAL,NONE,AK,ALASKA,BRISTOL BAY,AK,...,NaN,NaN,NaN,NaN,NaN,TIE,NaN,NaN,NaN,NaN
15,50031.5*C,SEAPLANE BASE,'AK81,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
24,50035.2*C,SEAPLANE BASE,'3C3,3/30/2017,AAL,NONE,AK,ALASKA,ANCHORAGE,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,50877.32*C,SEAPLANE BASE,'MFN,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
734,50877.01*C,SEAPLANE BASE,'2X2,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,FAA-EST,00:00:00,STATE,00:00:00,NaN,TIE,CHTR,Y,NaN,NaN
737,50905.*C,SEAPLANE BASE,'68A,3/30/2017,AAL,NONE,AK,ALASKA,WRANGELL-PETERSBURG,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN

In [0]:
df_facilities.sort_values(by = "ARPElevation", ascending = False)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
584,50739.1*A,AIRPORT,'AA09,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
630,50738.20*A,AIRPORT,'93AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,CARGO,Y,NaN,NaN
265,50324.6*A,AIRPORT,'4Z5,3/30/2017,AAL,NONE,AK,ALASKA,SOUTHEAST FAIRBANKS,AK,...,FAA OE/AAA,00:00:00,FAA OE/AAA,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
582,50738.01*A,AIRPORT,'2AK7,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,50439.18*A,AIRPORT,'AK80,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,50196.3*C,SEAPLANE BASE,'ELV,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAEL,NaN
516,50680.*C,SEAPLANE BASE,'A23,3/30/2017,AAL,NONE,AK,ALASKA,WRANGELL-PETERSBURG,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
363,50455.6*C,SEAPLANE BASE,'13Z,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
382,50489.*C,SEAPLANE BASE,'MTM,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,Y,PAMM,NaN
628,50773.5*C,SEAPLANE BASE,'AK62,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN

In [0]:
df_facilities.sort_values(by = "ARPElevation", ascending = False).head(n = 5)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
584,50739.1*A,AIRPORT,'AA09,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
630,50738.20*A,AIRPORT,'93AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,CARGO,Y,NaN,NaN
265,50324.6*A,AIRPORT,'4Z5,3/30/2017,AAL,NONE,AK,ALASKA,SOUTHEAST FAIRBANKS,AK,...,FAA OE/AAA,00:00:00,FAA OE/AAA,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
582,50738.01*A,AIRPORT,'2AK7,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,50439.18*A,AIRPORT,'AK80,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN

In [0]:
df_facilities['ARPElevation'].describe()

Out[15]: count     751.000000
mean      425.932091
std       657.117067
min         0.000000
25%        45.000000
50%       170.000000
75%       440.000000
max      3984.000000
Name: ARPElevation, dtype: float64

In [0]:
df_facilities["ARPElevation"].mean()

Out[16]: 425.93209054593876

In [0]:
df_seaplane = df_facilities[df_facilities["Type"] == "SEAPLANE BASE"]

In [0]:
print(df_seaplane.to_excel("./seaplane.xlsx"))

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<command-3759598440925115> in <cell line: 1>()
----> 1 print(df_seaplane.to_excel("temp/seaplane.xlsx"))

/databricks/python/lib/python3.9/site-packages/pandas/core/generic.py in to_excel(self, excel_writer, sheet_name, na_rep, float_format, columns, header, index, index_label, startrow, startcol, engine, merge_cells, encoding, inf_rep, verbose, freeze_panes, storage_options)
   2282             inf_rep=inf_rep,
   2283         )
-> 2284         formatter.write(
   2285             excel_writer,
   2286             sheet_name=sheet_name,

/databricks/python/lib/python3.9/site-packages/pandas/io/formats/excel.py in write(self, writer, sheet_name, startrow, startcol, freeze_panes, engine, storage_options)
    832             # error: Cannot instantiate abstract class 'ExcelWriter' with abstract
    833             # attributes 'engine', 'save', 'supported_extensions' and 'write_cells'
--> 834             writer = ExcelWriter(  # type: ignore[abstract]
    835                 writer, engine=engine, storage_options=storage_options
    836             )

/databricks/python/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py in __init__(self, path, engine, date_format, datetime_format, mode, storage_options, if_sheet_exists, engine_kwargs, **kwargs)
     50         engine_kwargs = combine_kwargs(engine_kwargs, kwargs)
     51
---> 52         super().__init__(
     53             path,
     54             mode=mode,

/databricks/python/lib/python3.9/site-packages/pandas/io/excel/_base.py in __init__(self, path, engine, date_format, datetime_format, mode, storage_options, if_sheet_exists, engine_kwargs, **kwargs)
    923         self.handles = IOHandles(cast(Buffer, path), compression={"copression": None})
    924         if not isinstance(path, ExcelWriter):
--> 925             self.handles = get_handle(
    926                 path, mode, storage_options=storage_options, is_text=False
    927             )

/databricks/python/lib/python3.9/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    709         else:
    710             # Binary mode
--> 711             handle = open(handle, ioargs.mode)
    712         handles.append(handle)
    713

FileNotFoundError: [Errno 2] No such file or directory: 'temp/seaplane.xlsx'